.PHONY: clean All

All:
	@echo "----------Building project:[ Prob_4 - Debug ]----------"
	@cd "Prob_4" && "$(MAKE)" -f  "Prob_4.mk"
clean:
	@echo "----------Cleaning project:[ Prob_4 - Debug ]----------"
	@cd "Prob_4" && "$(MAKE)" -f  "Prob_4.mk" clean
