.PHONY: clean All

All:
	@echo "----------Building project:[ ex2_1 - Debug ]----------"
	@cd "/Users/siyuan/Desktop/C/Exercise/Chapter2/ex2_1" && "$(MAKE)" -f  "ex2_1.mk"
clean:
	@echo "----------Cleaning project:[ ex2_1 - Debug ]----------"
	@cd "/Users/siyuan/Desktop/C/Exercise/Chapter2/ex2_1" && "$(MAKE)" -f  "ex2_1.mk" clean
